"""empty message

Revision ID: 74862967cdbd
Revises: 
Create Date: 2021-03-12 14:22:21.265695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74862967cdbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace',
    sa.Column('id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller',
    sa.Column('id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('trade_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=8), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_product',
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_product')
    op.drop_table('address')
    op.drop_table('seller')
    op.drop_table('product')
    op.drop_table('marketplace')
    op.drop_table('category')
    # ### end Alembic commands ###
